- debug:
    msg: "environment: {{environment_name}}: Configuring application launcher"

- name: "Create {{springboot_application.service_name}}.service"
  template: 
    src: application.service.j2
    dest: "/etc/systemd/system/{{springboot_application.service_name}}.service"
    
- name: Force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: Make sure a service is running
  systemd:
    state: restarted
    enabled: yes
    name: "{{springboot_application.service_name}}"
